spring:
  loginfilter:
    allowurls: /
  profiles:
    active: sit
#    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
server:
  port: 7889